// SneakyLink stock — generated from SL_Pricelist_1.xlsx (Aug 2026).
// Each size entry: { size, qty, price? } — price overrides the product base price.
// Images live in images/products/. Edit this file to update stock.
const PRODUCTS = [
  {
    id: "rose-whisper-dunk",
    brand: "Nike",
    name: "Dunk Low Rose Whisper (W)",
    basePrice: 1500,
    category: "sneakers",
    sizes: [{ size: "UK7", qty: 1 }],
    images: ["rose-whisper-dunk-1.jpg", "rose-whisper-dunk-2.jpg", "rose-whisper-dunk-3.jpg"],
  },
  {
    id: "nocta-tshirt",
    brand: "NOCTA",
    name: "Distant Regards T-Shirt",
    basePrice: 1000,
    category: "apparel",
    sizes: [{ size: "XS", qty: 1 }],
    images: ["nocta-tshirt-1.jpg", "nocta-tshirt-2.jpg"],
  },
  {
    id: "aj2-off-white-black",
    brand: "Jordan",
    name: "Off-White x Air Jordan 2 Low Black",
    basePrice: 4000,
    category: "sneakers",
    sizes: [{ size: "UK6.5", qty: 1 }],
    images: ["aj2-off-white-black-1.jpg", "aj2-off-white-black-2.jpg", "aj2-off-white-black-3.jpg"],
  },
  {
    id: "dunk-uv-reactive-gs",
    brand: "Nike",
    name: "Dunk Low UV Reactive (GS)",
    basePrice: 2000,
    category: "sneakers",
    sizes: [{ size: "UK3", qty: 1 }],
    images: ["dunk-uv-reactive-gs-1.jpg"],
  },
  {
    id: "yeezy-700-v3-copper-fade",
    brand: "Yeezy",
    name: "Yeezy 700 V3 Copper Fade",
    basePrice: 4900,
    category: "sneakers",
    sizes: [
      { size: "UK7.5", qty: 1 },
      { size: "UK8", qty: 2 },
      { size: "UK11.5", qty: 1, price: 5500 },
    ],
    images: ["yeezy-700-v3-copper-fade-1.jpg", "yeezy-700-v3-copper-fade-2.jpg", "yeezy-700-v3-copper-fade-3.jpg"],
  },
  {
    id: "aj4-black-cat",
    brand: "Jordan",
    name: "Air Jordan 4 Black Cat",
    basePrice: 5500,
    category: "sneakers",
    sizes: [{ size: "UK11", qty: 1 }],
    images: ["aj4-black-cat-1.jpg", "aj4-black-cat-2.jpg", "aj4-black-cat-3.jpg"],
  },
  {
    id: "yeezy-foam-onyx",
    brand: "Yeezy",
    name: "Yeezy Foam RNNR Onyx",
    basePrice: 1300,
    category: "sneakers",
    sizes: [{ size: "UK12", qty: 1 }],
    images: ["yeezy-foam-onyx-1.jpg", "yeezy-foam-onyx-2.jpg", "yeezy-foam-onyx-3.jpg"],
  },
  {
    id: "aj1-bred-85",
    brand: "Jordan",
    name: "Air Jordan 1 High OG '85 Bred",
    basePrice: 5500,
    category: "sneakers",
    sizes: [
      { size: "UK8", qty: 1 },
      { size: "UK9", qty: 2 },
    ],
    images: ["aj1-bred-85-1.jpg", "aj1-bred-85-2.jpg", "aj1-bred-85-3.jpg"],
  },
  {
    id: "yeezy-qntm-flash-orange",
    brand: "Yeezy",
    name: "Yeezy QNTM Flash Orange",
    basePrice: 2300,
    category: "sneakers",
    sizes: [
      { size: "UK7.5", qty: 1 },
      { size: "UK8", qty: 1 },
      { size: "UK9.5", qty: 1 },
      { size: "UK10", qty: 1 },
    ],
    images: ["yeezy-qntm-flash-orange-1.jpg"],
  },
  {
    id: "yeezy-qntm-amber-tint",
    brand: "Yeezy",
    name: "Yeezy QNTM Amber Tint",
    basePrice: 2300,
    category: "sneakers",
    sizes: [
      { size: "UK8.5", qty: 1 },
      { size: "UK9.5", qty: 1 },
      { size: "UK10", qty: 2 },
    ],
    images: ["yeezy-qntm-amber-tint-1.jpg"],
  },
  {
    id: "aj4-seafoam",
    brand: "Jordan",
    name: "Air Jordan 4 Seafoam (W)",
    basePrice: 4500,
    category: "sneakers",
    sizes: [{ size: "UK6.5", qty: 1 }],
    images: ["aj4-seafoam-1.jpg", "aj4-seafoam-2.jpg", "aj4-seafoam-3.jpg"],
  },
  {
    id: "aj4-wyws-amm",
    brand: "Jordan",
    name: "A Ma Maniére x AJ4 While You Were Sleeping",
    basePrice: 5000,
    category: "sneakers",
    sizes: [{ size: "UK8", qty: 1 }],
    images: ["aj4-wyws-amm-1.jpg", "aj4-wyws-amm-2.jpg", "aj4-wyws-amm-3.jpg"],
  },
  {
    id: "aj4-midnight-navy",
    brand: "Jordan",
    name: "Air Jordan 4 Midnight Navy",
    basePrice: 5500,
    category: "sneakers",
    sizes: [{ size: "UK9.5", qty: 1 }],
    images: ["aj4-midnight-navy-1.jpg", "aj4-midnight-navy-2.jpg", "aj4-midnight-navy-3.jpg"],
  },
  {
    id: "yeezy-350-onyx",
    brand: "Yeezy",
    name: "Yeezy Boost 350 V2 Onyx",
    basePrice: 3000,
    category: "sneakers",
    sizes: [{ size: "UK12.5", qty: 1 }],
    images: ["yeezy-350-onyx-1.jpg", "yeezy-350-onyx-2.jpg", "yeezy-350-onyx-3.jpg"],
  },
  {
    id: "yeezy-350-bone",
    brand: "Yeezy",
    name: "Yeezy Boost 350 V2 Bone",
    basePrice: 3000,
    category: "sneakers",
    sizes: [{ size: "UK11", qty: 1 }],
    images: ["yeezy-350-bone-1.jpg", "yeezy-350-bone-2.jpg", "yeezy-350-bone-3.jpg"],
  },
  {
    id: "aj4-flight-club",
    brand: "Jordan",
    name: "Air Jordan 4 Flight Club (2026)",
    basePrice: 4700,
    category: "sneakers",
    sizes: [
      { size: "UK6", qty: 4, price: 5200 },
      { size: "UK9", qty: 2 },
      { size: "UK10", qty: 5 },
      { size: "UK11", qty: 1 },
      { size: "UK12", qty: 1, price: 5200 },
    ],
    images: ["aj4-flight-club-1.jpg", "aj4-flight-club-2.jpg", "aj4-flight-club-3.jpg"],
  },
];

const SHIPPING_OPTIONS = [
  {
    id: "pudo",
    label: "PUDO Locker-to-Locker",
    price: 130,
    hint: "Delivered to your nearest PUDO locker",
  },
  {
    id: "postnet",
    label: "PostNet-to-PostNet",
    price: 150,
    hint: "Collect at your nearest PostNet branch",
  },
];
